parameters:
    contact.attributes:
        subject: 'Contact Form'
        to: 'hello@domain.com'
        from: 'contact_form@domain.com'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Mailer\ContactMailer:
        arguments:
            $parameters: '%contact.attributes%'
